Add files : index.html, style.css and .gitignore
sarmade/Hello pull request #1
Opened 2022-04-19 17:52 UTC by sarmade

2022-04-19 18:29 UTC, m05e5 requested changes
Hi @sarmade , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to add or improve
  - [ ] Please make sure to have a professional README file. This is a general requirement. I will highly recommend following the [microverse template](https://github.com/microverseinc/readme-template)
  
  - [ ] Please make sure Linter is set up correctly for this repository and all checks are green. You can find the linter template [here](https://github.com/microverseinc/linters-config)
  
  - [ ] As part of the requirement, its better to put your "< h1 >" tag in a "< header >" tag for your code to be more semantic and for SEO
  
  - [ ] Your Pull Request should have a summary describing introduced changes in more detail (you can edit it at the top of the PR)

_I'm sure you can do it just keep it up_
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-19 18:30 UTC, m05e5 commented on index.html
> +</body>
As part of the requirement, its better to put your "< h1 >" tag in a "< header >" tag for your code to be more semantic and for SEO

2022-04-20 11:25 UTC, merged

2022-04-20 12:41 UTC, sarmade commented
@m05e5
When I make the check button, github told me :
Workflow runs completed with no job.

That mean that is ok or not ?

2022-04-20 12:46 UTC, sarmade commented
I have created by mistake 5 pull requests.
This is an error or not?

2022-04-20 13:16 UTC, sarmade commented
@m05e5
You should use this link now: https://github.com/sarmade/Hello/pull/7